package {{api.ns}};

import java.util.*;


// Do not edit, auto generated by api-kit, kanzhun.com.
// {{api.ts}}

public interface IHandler {
    // Called before every function. Use cases: setup context, authentication return false to abort further execution.
    public boolean before(Context context);

    // Called after every function. One use case is logging
    public void after(Context context);

{% for func in funcs %}
    // {{func.method}} {{func.uri}}{%if func.query %}?{{func.query}}{% end %}
    public {{func.ret.type('java')}} {{func.name}}(Context context,
        {% for idx, arg in enumerate(func.params) %} {{arg.type('java')}} {{arg.name}}{% if idx != len(func.params) -1 %}, {% end %}{% end %});
{% end %}
}
