package {{api.ns}};

import org.json.*;

// Do not edit, auto generated by api-kit, kanzhun.com.
// {{api.ts}}

public class Utils {
    static int geti32(JSONObject obj, String name) throws JSONException {
        return obj.has(name) ? obj.getInt(name) : 0;
    }

    static long geti64(JSONObject obj, String name) throws JSONException {
        return obj.has(name) ? obj.getLong(name) : 0;
    }

    static String getstring(JSONObject obj, String name) throws JSONException {
        return obj.has(name) ? obj.getString(name) : "";
    }

    static boolean getbool(JSONObject obj, String name) throws JSONException {
        return obj.has(name) && obj.getBoolean(name);
    }

    static double getfloat64(JSONObject obj, String name) throws JSONException {
        return obj.has(name) ? obj.getDouble(name) : 0;
    }

    static float getfloat32(JSONObject obj, String name) throws JSONException {
        return obj.has(name) ? (float) obj.getDouble(name) : 0f;
    }

    static int arri32(JSONArray arr, int idx) throws JSONException {
        return arr.getInt(idx);
    }

    static long arri64(JSONArray arr, int idx) throws JSONException {
        return arr.getLong(idx);
    }

    static boolean arrbool(JSONArray arr, int idx) throws JSONException {
        return arr.getBoolean(idx);
    }

    static String arrstring(JSONArray arr, int idx) throws JSONException {
        return arr.getString(idx);
    }

    static double arrfloat64(JSONArray arr, int idx) throws JSONException {
        return arr.getDouble(idx);
    }

    static float arrfloat32(JSONArray arr, int idx) throws JSONException {
        return (float) arr.getDouble(idx);
    }
}
