#import <Foundation/Foundation.h>

// Do not edit, auto generated by api-kit, kanzhun.com.
// {{api.ts}}

{% for b in api.structs %}
@interface {{b.name}} : NSObject
{% for f in b.fields %}
@property ({% if '*' in f.type('objc') %}strong, {% end %}nonatomic) {{f.type('objc')}}{{f.name}}; {% if f.optional %} // optional {% end %}
{% end %}
- (id)initWithDict:(NSDictionary *)dict;
- (NSDictionary *) toJSON;
- (id)init: {% for idx, f in enumerate(b.requires) %} {% if idx > 0 %} {{f.name}}:{% end %} ({{f.type('objc')}}){{f.name}} {% end %};
@end

{% end %}